name: Python CI

# S'executa en les pull requests a la branca 'main'
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pylint
      run: |
        pip install pylint
        pylint $(find . -name "*.py")

    - name: Run tests with coverage
      run: |
        pip install coverage
        coverage run -m unittest discover
        coverage report
