name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Build Docker image
      run: |
        docker build -t main.py .

    - name: Install dependencies
      run: |
        docker run --rm python-app pip install --upgrade pip
        docker run --rm python-app pip install -r requirements.txt

    - name: Run pylint
      run: |
        docker run --rm python-app pylint $(find . -name "*.py")

    - name: Run tests with coverage
      run: |
        docker run --rm python-app sh -c "coverage run -m unittest discover && coverage report"

